default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] + '_test' %>

production:
  <<: *default
